### PR TITLE
Include dat files in PHAR compiling

### LINKED ISSUE #128: Phar is missing dat files
`PHP Warning:  file(phar:///fink.phar/vendor/amphp/http-client-cookies/src/Internal/../../res/public_suffix_list.dat): Failed to open stream: phar error: "vendor/amphp/http-client-cookies/res/public_suffix_list.dat" is not a file in phar "/fink.phar" in phar:///fink.phar/vendor/amphp/http-client-cookies/src/Internal/PublicSuffixList.php on line 49`
when executing the phar

### PR DESCRIPTION
**Pull request by M-arcus**
Fixes https://github.com/dantleech/fink/issues/128

### CODE REVIEW

**Comment by dantleech** [comment]
Thanks!

**Comment by M-arcus** [comment]
@dantleech 
I'm using the phar in a docker image, can you please post update 0.10.4 with the updated phar?

**Comment by dantleech** [comment]
tagged and bumped to PHP 8.0

**Comment by M-arcus** [comment]
@dantleech 
Thank you :+1:

**Pull request merged**
